package vista;

import controlador.Nacionalidad;
import controlador.conexionOracle;
import controlador.manejaExperto;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.experto;

/**
 *
 * @author jprecreativo
 */
public class Consultar extends Screen 
{
    private final conexionOracle co;
    
    /**
     * Creates new form Consultar
     */
    public Consultar(conexionOracle co)
    {
        initComponents();
        
        this.co = co;
        
        super.inicialize(this.getWidth(), this.getHeight(), "Consultar expertos por nacionalidad");
        this.obtenerNacionalidades();
        
        cb_nacionalidades.addItemListener(new Nacionalidad(co));
    }
    
    public static void rellenarTabla(ArrayList<experto> expertos)
    {
        DefaultTableModel model = (DefaultTableModel) jt_Datos.getModel();
        
        if(model.getRowCount() > 0)
            for(int i = model.getRowCount() - 1; i >= 0; i--)
                model.removeRow(i);
        
        expertos.stream().forEach((e) -> model.addRow(new Object[] {e.getCodExperto(),
                                                                    e.getNombre(),
                                                                    e.getPais(),
                                                                    e.getSexo(),
                                                                    e.getEspecialidad()}));
    }

    private void obtenerNacionalidades()
    {
        try 
        {
            ResultSet nacionalidades = Nacionalidad.obtenerNacionalidades();
            
            while(nacionalidades.next())
                cb_nacionalidades.addItem(nacionalidades.getString(1));
            
            String primeraNacionalidad = cb_nacionalidades.getItemAt(0);
            
            Consultar.rellenarTabla(new manejaExperto(co).listaExpertosPorPais(primeraNacionalidad));
        } 
        
        catch (SQLException e) 
        {
            System.out.println("Error: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_nacionalidades = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Datos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Elige una nacionalidad:");

        jt_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODEXPERTO", "NOMBRE", "PAIS", "SEXO", "ESPECIALIDAD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_Datos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jt_Datos);
        if (jt_Datos.getColumnModel().getColumnCount() > 0) {
            jt_Datos.getColumnModel().getColumn(0).setResizable(false);
            jt_Datos.getColumnModel().getColumn(1).setResizable(false);
            jt_Datos.getColumnModel().getColumn(2).setResizable(false);
            jt_Datos.getColumnModel().getColumn(3).setResizable(false);
            jt_Datos.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cb_nacionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_nacionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_nacionalidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jt_Datos;
    // End of variables declaration//GEN-END:variables
}
