package vista;

import controlador.manejaColabora;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Pantalla para ver las colaboraciones de un caso en concreto.
 * @author jprecreativo
 */
public class G_Colaboraciones extends Screen 
{
    public G_Colaboraciones() 
    {
        initComponents();
        
        super.inicialize(this.getWidth(), this.getHeight(), "Gestión de colaboraciones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_datos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tf_codCaso = new javax.swing.JTextField();
        bt_mostar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jt_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código del experto", "Nombre del caso", "Especialidad del experto", "Colaboración"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_datos);
        if (jt_datos.getColumnModel().getColumnCount() > 0) {
            jt_datos.getColumnModel().getColumn(0).setResizable(false);
            jt_datos.getColumnModel().getColumn(1).setResizable(false);
            jt_datos.getColumnModel().getColumn(2).setResizable(false);
            jt_datos.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Introduce el código de un caso:");

        bt_mostar.setText("Mostrar colaboraciones");
        bt_mostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mostarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_codCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_mostar)
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_codCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_mostar))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /***
     * Rellena la tabla con los datos de las colaboraciones.
     */
    private void rellenarTabla()
    {
        DefaultTableModel model = (DefaultTableModel) jt_datos.getModel();
        
        this.limpiarTabla(model);
        this.obtenerColaboraciones(model);
    }
    
    /***
     * Borra el contenido de la tabla.
     * @param model Modelo de la tabla.
     */
    private void limpiarTabla(DefaultTableModel model)
    {
        if(model.getRowCount() > 0)
            for(int i = model.getRowCount() - 1; i >= 0; i--)
                model.removeRow(i);
    }
    
    /***
     * Obtiene las colaboraciones de un caso en concreto. Si el caso no existe, se le notifica al usuario.
     * @param model Modelo de la tabla.
     */
    private void obtenerColaboraciones(DefaultTableModel model)
    {
        try 
        {
            ResultSet colaboraciones = new manejaColabora().listaColaboradoresPorCaso(tf_codCaso.getText());
            
            if(colaboraciones.isBeforeFirst())   // Si hay datos en el ResultSet.
                while(colaboraciones.next())
                {
                    String codExperto = colaboraciones.getString(1);
                    String nombreCaso = colaboraciones.getString(2);
                    String especialidad = colaboraciones.getString(3);
                    String colaboración = colaboraciones.getString(4);

                    model.addRow(new Object[] {codExperto, nombreCaso, especialidad, colaboración});
                }
            
            else
                JOptionPane.showMessageDialog(this, "Código de caso inexistente.", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
        catch (SQLException e) 
        {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    private void bt_mostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mostarActionPerformed
        
        this.rellenarTabla();
    }//GEN-LAST:event_bt_mostarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_mostar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_datos;
    private javax.swing.JTextField tf_codCaso;
    // End of variables declaration//GEN-END:variables
}
